return {
  "catppuccin/nvim",
  lazy = false,
  priority = 1000,
  name = "catppuccin",
  opts = {
    color_overrides = {
      mocha = {
        rosewater = "#EA6962",
        flamingo = "#EA6962",
        pink = "#D3869B",
        mauve = "#D3869B",
        red = "#EA6962",
        maroon = "#EA6962",
        peach = "#BD6F3E",
        yellow = "#D8A657",
        green = "#A9B665",
        teal = "#89B482",
        sky = "#89B482",
        sapphire = "#89B482",
        blue = "#7DAEA3",
        lavender = "#7DAEA3",
        text = "#D4BE98",
        subtext1 = "#BDAE8B",
        subtext0 = "#A69372",
        overlay2 = "#8C7A58",
        overlay1 = "#735F3F",
        overlay0 = "#958272",
        surface2 = "#4B4F51",
        surface1 = "#2A2D2E",
        surface0 = "#232728",
        base = "#1D2021",
        mantle = "#191C1D",
        crust = "#151819",
      },
    },
    styles = {},
    transparent_background = true,
    show_end_of_buffer = false,
    integrations = {
      cmp = true,
      gitsigns = true,
      nvimtree = true,
      treesitter = true,
      telescope = {
        enabled = true,
      },
      lsp_trouble = false,
    },
    custom_highlights = function(colors)
      return {
        CursorLineNr = { fg = colors.mauve },
        IndentBlanklineChar = { fg = colors.surface0 },
        IndentBlanklineContextChar = { fg = colors.surface2 },
        GitSignsChange = { fg = colors.peach },
        GitSignsCurrentLineBlame = { fg = "#9E8069", italic = true },
        NvimTreeIndentMarker = { link = "IndentBlanklineChar" },
        NvimTreeExecFile = { fg = colors.text },
        Visual = { fg = "#9E8069" },
        FloatBorder = { fg = "#303030" },
        Comment = { fg = "#9E8069" },
        -- Terraform LSP semantic token highlights
        ["@lsp.type.enumMember.terraform"] = { fg = colors.peach },
        ["@type.builtin.terraform"] = { fg = colors.yellow },
        -- Treesitter highlight groups (Neovim 0.11+ native groups)
        ["@variable"] = { fg = colors.text },
        ["@variable.builtin"] = { fg = colors.red },
        ["@variable.parameter"] = { fg = colors.maroon },
        ["@variable.member"] = { fg = colors.lavender },
        ["@constant"] = { fg = colors.peach },
        ["@constant.builtin"] = { fg = colors.peach },
        ["@module"] = { fg = colors.lavender },
        ["@label"] = { fg = colors.sapphire },
        ["@string"] = { fg = colors.green },
        ["@string.escape"] = { fg = colors.pink },
        ["@string.regexp"] = { fg = colors.peach },
        ["@character"] = { fg = colors.teal },
        ["@boolean"] = { fg = colors.peach },
        ["@number"] = { fg = colors.peach },
        ["@type"] = { fg = colors.yellow },
        ["@type.builtin"] = { fg = colors.yellow },
        ["@attribute"] = { fg = colors.peach },
        ["@property"] = { fg = colors.lavender },
        ["@function"] = { fg = colors.blue },
        ["@function.builtin"] = { fg = colors.peach },
        ["@function.macro"] = { fg = colors.teal },
        ["@function.method"] = { fg = colors.blue },
        ["@constructor"] = { fg = colors.sapphire },
        ["@operator"] = { fg = colors.sky },
        ["@keyword"] = { fg = colors.mauve },
        ["@keyword.modifier"] = { fg = colors.mauve },
        ["@keyword.type"] = { fg = colors.mauve },
        ["@keyword.coroutine"] = { fg = colors.mauve },
        ["@keyword.function"] = { fg = colors.mauve },
        ["@keyword.operator"] = { fg = colors.mauve },
        ["@keyword.import"] = { fg = colors.mauve },
        ["@keyword.repeat"] = { fg = colors.mauve },
        ["@keyword.return"] = { fg = colors.mauve },
        ["@keyword.exception"] = { fg = colors.mauve },
        ["@keyword.conditional"] = { fg = colors.mauve },
        ["@punctuation.delimiter"] = { fg = colors.overlay2 },
        ["@punctuation.bracket"] = { fg = colors.overlay2 },
        ["@punctuation.special"] = { fg = colors.sky },
        ["@comment"] = { fg = "#9E8069" },
        ["@comment.todo"] = { fg = colors.base, bg = colors.yellow },
        ["@comment.warning"] = { fg = colors.base, bg = colors.peach },
        ["@comment.error"] = { fg = colors.base, bg = colors.red },
        ["@markup.heading"] = { fg = colors.blue, bold = true },
        ["@markup.link"] = { fg = colors.blue },
        ["@markup.link.url"] = { fg = colors.rosewater, underline = true },
        ["@markup.raw"] = { fg = colors.teal },
        ["@markup.list"] = { fg = colors.mauve },
        ["@diff.plus"] = { fg = colors.green },
        ["@diff.minus"] = { fg = colors.red },
        ["@diff.delta"] = { fg = colors.peach },
        ["@tag"] = { fg = colors.mauve },
        ["@tag.attribute"] = { fg = colors.teal },
        ["@tag.delimiter"] = { fg = colors.sky },
      }
    end,
  },
  config = function(_, opts)
    require("catppuccin").setup(opts)
    vim.cmd([[
      set guicursor=n-v-c:block-CursorInsert,i-ci-ve:hor20-CursorInsert,r-cr:hor20-CursorInsert,o:hor50-CursorInsert
      highlight CursorInsert guifg=NONE guibg=#9E8069
      highlight Cursor guifg=NONE guibg=#9E8069
      colorscheme catppuccin
    ]])
  end,
}
